### PR TITLE
Clean up `Pitch Compass` class

### LINKED ISSUE #102: Rotate Pitch Compass so the root of the key is at the top
I think it would be helpful if the Pitch Compass view displayed the root of the selected key at the top.  This way, the tonic is always at the top, the major 3rd is at 4 o'clock, the 5th is at 7 o'clock.

It might also be interesting to try hiding some of the note labels when you select a scale from the combo box (to match how the Pitch Contour view does the same thing).

### PR DESCRIPTION
**Pull request by mself**
- Added enum class `CompassMode` to track modes (only `Mode2` works at the moment)
- Removed unused member `m_move_needle`
- Use member initialization
- Remove unused include files
- Make forced updates explicit
- Add missing `delete` in destructors
- Simplify control flow to remove "early return"

### CODE REVIEW

**Comment by quicky2000** [comment]
Please keep mode 1 and 2, I would like to try to make them work

**Comment by mself** [comment]
OK, I put the code for the other modes back.  They don't do much at the moment and I didn't try to fix them.  I'm not sure what they are supposed to do.

**Comment by quicky2000** [comment]
I' sorry but this commit is very hard to read due to the number of changes at the same time...
Could you split it in several commits to make it easier to understand:
* Added enum class CompassMode to track modes (only Mode2 works at the moment)
* Removed unused member m_move_needle
*  Use member initialization
*  Moved creation of the compass scale into new method setCompassScale
etc etc

**Comment by quicky2000** [comment]
```
    // Force the compass to invalidate its cache and redraw.
    // QwtDial::invalidateCache() is a protected member.
    // TODO: Is there a cleaner way to do this?
    m_compass->setMode(QwtCompass::RotateScale);
    m_compass->setMode(QwtCompass::RotateNeedle);
```
call blank() and redraw ?

**Comment by mself** [comment]
OK, I updated the branch to have just the clean up changes and broken into separate commits.  I'll submit a separate PR for the feature enhancement.

**Pull request merged**
