### PR TITLE
Qt5qwt6 migration

### PR DESCRIPTION
**Pull request by nsauzede**
Experimental QT5+QWT6 port

### CODE REVIEW

**Comment by nsauzede** [comment]
how can I add a label to this PR ?

**Comment by nsauzede** [comment]
it doesn't survive TravisCI :-(
close and will reopen

**Comment by quicky2000** [comment]
Travis is still failing ?
Changeset is too big. Could you split ip per ported feature ?
For example there are some changes related to migration Qwt migration that I think are already covered by branch Qwt6_migration

**Comment by nsauzede** [comment]
can you please start a review ? (at least initiate the process ?)
just curious to see how it would proceed.. as I'd push more commits..
thanks

**Comment by quicky2000** [comment]
I request split commits to be able to start a review...

**Comment by nsauzede** [comment]
ok will see what I can do thanks

**Comment by nsauzede** [comment]
just rebased on master
will try and split

**Comment by nsauzede** [comment]
would it be possible to first merge qwt6_integration to master ? this would simplify this current PR
I mean https://github.com/quicky2000/tartini/pull/16

**Comment by quicky2000** [comment]
Hi,

I merged Qt4_migration and qwt6_integration in master branch in repository tartini_exp ( https://github.com/quicky2000/tartini_exp )
Could you do the pull request on it so I can prepare Travis.
Once validated and ready we will integrate Pull Request in this repository

**Comment by quicky2000** [comment]
Hello, Qt4_migration and qwt6_integration has been merged in master.
Could you rebase on it ?

**Comment by nsauzede** [comment]
Sure will do
Thanks

**Comment by nsauzede** [comment]
split/rebase done

**Comment by quicky2000** [comment]
Integration done, thanks for your contribution !

**Pull request merged**
